FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./api /app/api
COPY ./db /app/db
COPY ./new_clients /app/new_clients
COPY ./services /app/services

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]